from fastapi import APIRouter

from app.schemas.travel import TravelRequest
from app.services.travel_service import generate_travel_guide

router = APIRouter(prefix="/api/travel", tags=["travel"])


@router.post("/request")
def receive_travel_request(request: TravelRequest):
    # API 层只负责接收请求和返回响应，具体生成逻辑交给 Service 层。
    guide = generate_travel_guide(request)

    return {
        "status": "success",
        "message": "Travel guide generated by backend mock service",
        "data": guide,
    }
