from fastapi import APIRouter, HTTPException

from app.schemas.guide import TravelGuide
from app.schemas.travel import TravelRequest
from app.services.export_service import export_travel_guide
from app.services.history_service import list_history, save_history
from app.services.travel_service import (
    TravelGuideGenerationError,
    generate_travel_guide,
)

router = APIRouter(prefix="/api/travel", tags=["travel"])


@router.post("/request")
def receive_travel_request(request: TravelRequest):
    # API 层只负责接收请求和返回响应，具体生成逻辑交给 Service 层。
    try:
        guide = generate_travel_guide(request)
        save_history(request, guide)
    except TravelGuideGenerationError as error:
        raise HTTPException(status_code=500, detail=str(error)) from error

    return {
        "status": "success",
        "message": "Travel guide generated by LLM agent",
        "data": guide,
    }


@router.get("/history")
def get_travel_history():
    return {"status": "success", "data": list_history()}


@router.post("/export/{export_format}")
def export_travel_guide_endpoint(export_format: str, guide: TravelGuide):
    try:
        data = export_travel_guide(guide, export_format)
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error

    return {"status": "success", "data": data}
