from fastapi import APIRouter, HTTPException

from app.schemas.travel import TravelRequest
from app.services.travel_service import (
    TravelGuideGenerationError,
    generate_travel_guide,
)

router = APIRouter(prefix="/api/travel", tags=["travel"])


@router.post("/request")
def receive_travel_request(request: TravelRequest):
    # API 层只负责接收请求和返回响应，具体生成逻辑交给 Service 层。
    try:
        guide = generate_travel_guide(request)
    except TravelGuideGenerationError as error:
        raise HTTPException(status_code=500, detail=str(error)) from error

    return {
        "status": "success",
        "message": "Travel guide generated by LLM agent",
        "data": guide,
    }
